=== astute22/spring/simple-xml/WebContent/dtd/product.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT products (product*)>
<!ELEMENT product (name,maker,price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT maker (#PCDATA)>
<!ELEMENT price (original,discount)>
<!ELEMENT original (#PCDATA)>
<!ELEMENT discount (#PCDATA)>

<!ATTLIST product serial ID #REQUIRED
				  category CDATA #IMPLIED>
<!ATTLIST price unit (원|달러|엔|유로|코루나|파운드) "원">

=== astute22/spring/simple-xml/WebContent/dtd/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "product.dtd" >
<products>
	<product serial="ph0001" category="맛폰">
		<name>갠역시</name>
		<maker>칠성</maker>
		<price unit="파운드">
			<original>1000</original>
			<discount>900</discount>
		</price>
	</product>
	<product serial="ph0002" category="맛폰">
		<name>사과폰</name>
		<maker>사과</maker>
		<price unit="달러">
			<original>1060</original>
			<discount>980</discount>
		</price>
	</product>
</products>
